Improvements to speech-to-function (R11)
kelsvilla/LegoMindstormsVSExtension pull request #9
Opened 2023-11-09 01:16 UTC by chauler

#Changes

Updated paths in pythonManager.ts and client01.ts to work cross-platform.
Modified initial_set_up_windows.sh to be a batch file instead, with correct batch syntax.
Added dependencies to repo to allow voice server to run correctly once initialized.
Began work on Mac issues, fixing the pip install error with PyAudio.

#Testing (Windows Only)

On VS Code, execute the "Run Extension" debug profile.
On the newly opened debug window, in the Action List, click on "Voice-command.start Streaming".
Upon receiving the "Please give your command. Listening..." notification, say the title of a command provided by Mind Reader (titles are what show up in the Access Menu on the left sidebar, for example)
Enter a python file and say one of the code-related functions (e.g. insert an if ladder, insert a for loop, insert a try ladder)
Say "Exit" to stop the server from listening.

2023-11-14 20:11 UTC, Kaiyan-Da-Man commented
![image](https://github.com/kelsvilla/LegoMindstormsVSExtension/assets/89543725/c29de40e-fb3d-4955-9c99-0398a866a248)

getting a timeout error. Is this error the intended behavior?

2023-11-14 20:14 UTC, Kaiyan-Da-Man commented
![image](https://github.com/kelsvilla/LegoMindstormsVSExtension/assets/89543725/9bfc7217-a6dd-4bed-a963-c7dc25d31419)
terminal opens when I press `Voice-command.start Streaming`. Any way to get rid of this?

2023-11-14 20:16 UTC, Kaiyan-Da-Man commented
Partially my fault, but I think we should remove the portaudio dependency for now since we have a solution for PyAudio. We can always add it back when we need it.

2023-11-14 20:21 UTC, Kaiyan-Da-Man requested changes

2023-11-14 20:21 UTC, Kaiyan-Da-Man commented on server.py
While you're here, might as well fix the typo on line 76. I think 'Sever' is supposed to be 'Server'

2023-11-15 01:33 UTC, chauler commented on server.py
Fixed. Also removed PyAudio and removed the terminal window from server startup. The timeout error is unintended, but is known and part of Sprint 3's plans.

2023-11-15 01:42 UTC, Kaiyan-Da-Man approved these changes
lgtm

2023-11-17 17:27 UTC, merged